{
  "$GMRoomUI":"",
  "%Name":"RoomUI",
  "children":[],
  "locked":false,
  "name":"RoomUI",
  "parent":{
    "name":"Project Template 3.0",
    "path":"Project Template 3.0.yyp",
  },
  "resourceType":"GMRoomUI",
  "resourceVersion":"2.0",
  "viewspaceChildren":[
    {"$GMRUILayer":"v1","%Name":"Layer_Game_over","alignItems":2,"children":[
        {"$GMRFlexPanel":"","%Name":"Death_window","alignItems":2,"children":[
            {"$GMRFlexPanel":"","%Name":"Title","alignItems":2,"children":[
                {"$GMRTextItem":"v2","%Name":"txt_game_over","alignment":0,"charSpacing":0.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_game_Over","path":"fonts/fnt_game_Over/fnt_game_Over.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"txt_game_over","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"Game Over","wrap":false,"x":0.0,"xorigin":0.0,"y":0.0,"yorigin":0.0,},
              ],"flexDirection":0,"height":{"unit":3,"value":19.0,},"justifyContent":1,"name":"Title","nodeColour":4282970714,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":116.0,},},
            {"$GMRFlexPanel":"","%Name":"Options","alignItems":2,"children":[
                {"$GMRFlexPanel":"","%Name":"Try_again","alignItems":2,"children":[
                    {"$GMRFlexPanel":"","%Name":"FlexPanel_1","alignItems":2,"children":[
                        {"$GMRTextItem":"v2","%Name":"text_56D05649","alignment":0,"charSpacing":0.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_hud_default","path":"fonts/fnt_hud_default/fnt_hud_default.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_56D05649","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"Try Again","wrap":false,"x":0.0,"xorigin":0.0,"y":0.0,"yorigin":0.0,},
                      ],"flexDirection":0,"height":{"unit":3,"value":19.0,},"justifyContent":1,"name":"FlexPanel_1","nodeColour":4282968818,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":116.0,},},
                    {"$GMRInstance":"v2","%Name":"inst_1D4D8E16","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps","stretchHeight":true,"stretchWidth":true,},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_1D4D8E16","objectId":{"name":"oButtonTryAgain","path":"objects/oButtonTryAgain/oButtonTryAgain.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":0.0,"y":0.0,},
                    {"$GMRSpriteGraphic":"v1","%Name":"s_btn_try_again","animationSpeed":1.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps","stretchHeight":true,"stretchWidth":true,},"frozen":false,"headPosition":0.0,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"name":"s_btn_try_again","resourceType":"GMRSpriteGraphic","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"spriteId":{"name":"sButton","path":"sprites/sButton/sButton.yy",},"x":0.0,"y":0.0,},
                  ],"flexDirection":0,"height":{"unit":3,"value":24.0,},"justifyContent":1,"name":"Try_again","nodeColour":4294101064,"paddingBottom":{"unit":1,"value":15.0,},"paddingLeft":{"unit":1,"value":15.0,},"paddingRight":{"unit":1,"value":15.0,},"paddingTop":{"unit":1,"value":15.0,},"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":64.0,},},
                {"$GMRFlexPanel":"","%Name":"Back_to_menu","alignItems":2,"children":[
                    {"$GMRFlexPanel":"","%Name":"FlexPanel_1","alignItems":2,"children":[
                        {"$GMRTextItem":"v2","%Name":"text_179CE64","alignment":0,"charSpacing":0.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_hud_default","path":"fonts/fnt_hud_default/fnt_hud_default.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_179CE64","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"Back to Menu","wrap":false,"x":0.0,"xorigin":0.0,"y":0.0,"yorigin":0.0,},
                      ],"flexDirection":0,"height":{"unit":3,"value":19.0,},"justifyContent":1,"name":"FlexPanel_1","nodeColour":4282968818,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":116.0,},},
                    {"$GMRInstance":"v2","%Name":"inst_7E9F6995","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps","stretchHeight":true,"stretchWidth":true,},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_7E9F6995","objectId":{"name":"oButtonBackToMenu","path":"objects/oButtonBackToMenu/oButtonBackToMenu.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":0.0,"y":0.0,},
                    {"$GMRSpriteGraphic":"v1","%Name":"s_btn_back_to_menu","animationSpeed":1.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps","stretchHeight":true,"stretchWidth":true,},"frozen":false,"headPosition":0.0,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"name":"s_btn_back_to_menu","resourceType":"GMRSpriteGraphic","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"spriteId":{"name":"sButton","path":"sprites/sButton/sButton.yy",},"x":0.0,"y":0.0,},
                  ],"flexDirection":0,"height":{"unit":3,"value":24.0,},"justifyContent":1,"name":"Back_to_menu","nodeColour":4294101064,"paddingBottom":{"unit":1,"value":15.0,},"paddingLeft":{"unit":1,"value":15.0,},"paddingRight":{"unit":1,"value":15.0,},"paddingTop":{"unit":1,"value":15.0,},"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":64.0,},},
              ],"flexDirection":2,"gapColumn":16.0,"height":{"unit":3,"value":100.0,},"justifyContent":1,"marginTop":{"unit":1,"value":20.0,},"name":"Options","nodeColour":4294068328,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":100.0,},},
            {"$GMRSpriteGraphic":"v1","%Name":"graphic_5B5251D3","animationSpeed":1.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps","stretchHeight":true,"stretchWidth":true,},"frozen":false,"headPosition":0.0,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"name":"graphic_5B5251D3","resourceType":"GMRSpriteGraphic","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"spriteId":{"name":"sWindowBg","path":"sprites/sWindowBg/sWindowBg.yy",},"x":0.0,"y":0.0,},
          ],"flexDirection":0,"height":{"unit":2,"value":100.0,},"justifyContent":1,"name":"Death_window","nodeColour":4282970806,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":2,"value":100.0,},},
      ],"flexDirection":0,"gridX":32,"gridY":32,"justifyContent":1,"name":"Layer_Game_over","nodeColour":4285526600,"resourceType":"GMRUILayer","resourceVersion":"2.0",},
  ],
  "visible":true,
}